apiVersion: v1
kind: Service
metadata:
  name: pythonweb-service
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - port: 8080
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 5000
      